import Link from "next/link";
import "./globals.css";
import { Analytics } from "@/components/analytics";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
          <header className="py-4">
            <nav className="text-sm container mx-auto  flex items-center justify-between">
              <Link href={"/"} className="text-bold text-xl font-display ">
                Framer Snipps
              </Link>
              <button className="bg-indigo-500 p-2 px-4">
                Explore Components
              </button>
            </nav>
          </header>
            <main className="container mx-auto mt-4">{children}</main>
          <Analytics />
      </body>
    </html>
  );
}
